### ISSUE TITLE
Force input format for postal code and housenumber

### ISSUE THREAD

**Issue by gijs** [nens/waterlabel-client#5]

**Comment by reinout** [comment]
:-) Moet ik vaker doen: testen door vrouwlief :-)

**Comment by gijs** [comment]
Zeker doen! Bedankt namens het dev team ;)

Fixed in https://github.com/nens/waterlabel-client/commit/af01da60e896e724353cdd5f421bb841136a7921 (zie https://github.com/nens/waterlabel-client/blob/master/CHANGELOG.md#060-2017-03-31)
